AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS MoviesKotlin API - movies.kotlin::movies-kotlin
Globals:
  Api:
    EndpointConfiguration: REGIONAL
Resources:
  MoviesKotlinFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: movies.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: build/distributions/movies-kotlin-0.1.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any
  Table:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      KeySchema:
        - AttributeName: title
          KeyType: HASH
        - AttributeName: releaseYear
          KeyType: RANGE
      TableName: movie

Outputs:
  MoviesKotlinApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: MoviesKotlinApi
